version: '3.8'

services:
  mysql:
    image: mysql:latest
    #restart: always
    container_name: ${CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./volume/:/var/lib/mysql