version: '3.8'

services:
  mysql:
    image: mysql:latest
    #restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
    ports:
      - '3306:3306'
    volumes:
      - ./volume/:/var/lib/mysql